services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: pthm_db
    volumes:
      - db_data:/var/lib/postgresql/data # Persistent volume for PostgreSQL data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: Passw0rd
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Persistent volume for pgAdmin data

volumes:
  db_data:
  pgadmin_data:
